command_timeout = 5000
scan_timeout = 500
add_newline = true
format = "$hostname$directory$git_branch$git_commit$conda$python$cmake$time$cmd_duration\n$status$character"

[hostname]
ssh_only = false

[directory]
truncate_to_repo = false
truncation_length = 5
style = "cyan"
before_repo_root_style = "dimmed white"
repo_root_style = "bold fg:green"


[directory.substitutions]
"/hpcscratch/0066tm/workspace" = "ws:"
"/hpcscratch/0066tm" = "~hpcscratch:"
"/hpcdata/0066tm" = "~hpcdata:"

[python]
disabled = false

[rlang]
disabled = true

[git_status]
disabled = false

[git_commit]
disabled = false
only_detached = false

[status]
disabled = false
format = "[$common_meaning $status]($style) "