command_timeout = 5000
scan_timeout = 500
add_newline = true
format = "$hostname$directory$git_branch$git_commit$conda$python$cmake$time$cmd_duration\n$status$character"

[hostname]
ssh_only = false

[directory]
truncate_to_repo = false
truncation_length = 5
style = "cyan"
before_repo_root_style = "dimmed white"
repo_root_style = "bold fg:green"


[directory.substitutions]
"/hpcscratch/0066tm/workspace" = "ws:"
"/hpcscratch/0066tm" = "scratch:"
"/hpcdata/0066tm" = "data:"

[python]
disabled = false

[rlang]
disabled = true

[git_status]
disabled = false

[git_commit]
disabled = false
only_detached = false

[status]
disabled = false
# show only the exit code and colour
format = "[$status]($style) "

[time]
disabled = false
time_format = "%a %Y-%m-%d %H:%M:%S"

[cmake]
disabled = false

[direnv]
disabled = true

[cmd_duration]
disabled = false
show_milliseconds = false
format = "(took [$duration]($style))"
style = "bold blue"
