#!/bin/bash
#SBATCH --account=tai-lng
#SBATCH --partition=cascadelake
#SBATCH --time 00:05:00
#SBATCH --job-name=test-job
#SBATCH --output=/hpcscratch/%u/log/%x-%j.log
set -e

cd ${HPCSCRATCHDIR}/workspace
printenv | sort
sleep 10


