https://phi.testweb.bp.com/oat/api/curve/DE.Baseload
Etna-Token: 2FF3BDB3-71AF-49DD-867D-FDFF3A6E1A44

###
https://phi.bpweb.bp.com/api/Curve/TTF
Etna-Token: 2FF3BDB3-71AF-49DD-867D-FDFF3A6E1A44

###
https://phi.bpweb.bp.com/api/swagger/v1/swagger.json